name       : perl-posix-strptime
version    : 0.13
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/G/GO/GOZER/POSIX-strptime-0.13.tar.gz : a818109829e35a4ac79677d68063865f40c87c99ca7f3a20890177a8f8e5c277
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : POSIX::strptime - Perl extension to the POSIX date parsing strptime(3) function
description: |
    POSIX::strptime - Perl extension to the POSIX date parsing strptime(3) function
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
